import "./globals.css";
import { Kanit } from 'next/font/google'

const kanit = Kanit({
  subsets: ['latin','thai'],
  variable: '--font-kanit',
  weight: ['400','600', '700'],
  display: 'swap',
})

export const metadata = {
  title: "Harnbill",
  description: "Generated by OMG-dev",
};

export default function RootLayout({ children }) {
  return (
    <html className={`${kanit.variable} font-sans`}>
      
      <head>
        <link rel="icon" href="/favicon.ico" sizes="32x32" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
          integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body>
        {/* <div>sHealder</div> */}
        {children}
        {/* <div>Folter</div> */}
      </body>
      
    </html>
    
  );
}
